feature(pu): add game_2048_env and configs
opendilab/DI-1024 pull request #1
Opened 2024-07-18 16:31 UTC by puyuan1996

- add game_2048_env and configs

2024-07-19 02:54 UTC, PaParaZz1 requested changes

2024-07-19 02:54 UTC, PaParaZz1 commented on agent/config/muzero_2048_config.py
> +from easydict import EasyDict
remove origin `test_env.py`

2024-07-19 02:54 UTC, PaParaZz1 commented on agent/config/muzero_2048_config.py
> +
update requirements.txt

2024-07-19 02:54 UTC, PaParaZz1 commented on agent/config/muzero_2048_config.py
> +    exp_name=f'data_muzero/game_2048_npct-{num_of_possible_chance_tile}_muzero_ns{num_simulations}_upc{update_per_collect}_rer{reanalyze_ratio}_bs{batch_size}_sslw2_seed0',
simplify name here, this repo does not need too many hyper-parameters adjustment.

2024-07-19 02:54 UTC, PaParaZz1 commented on agent/config/muzero_2048_config.py
> +
update readme

2024-07-19 02:54 UTC, PaParaZz1 commented on agent/config/muzero_2048_config.py
> +    env=dict(
add a basic training curve

2024-07-22 10:18 UTC, puyuan1996 commented on agent/config/muzero_2048_config.py
> +    env=dict(
done

2024-07-22 12:50 UTC, zjowowen commented on agent/envs/game_2048_env.py
> +          - If 'obs_type' is set to 'encode_observation' (default):
'encode_observation'->'raw_encoded_board'?

2024-07-23 02:39 UTC, puyuan1996 commented on agent/envs/game_2048_env.py
> +          - If 'obs_type' is set to 'encode_observation' (default):
done

2024-07-23 10:34 UTC, PaParaZz1 approved these changes

2024-07-23 10:34 UTC, merged